# Generated by Django 3.2.20 on 2024-03-08 23:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=16)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to=products.models.ruta)),
            ],
        ),
    ]
